apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-processor
  labels:
    app: event-processor
spec:
  replicas: 3
  selector:
    matchLabels:
      app: event-processor
  template:
    metadata:
      labels:
        app: event-processor
    spec:
      containers:
      - name: event-processor
        image: ${ECR_REGISTRY}/event-processor:latest
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          value: redis-master
        - name: REDIS_PORT
          value: "6379"
        - name: REGION
          valueFrom:
            configMapKeyRef:
              name: cluster-config
              key: region
        - name: ENVIRONMENT
          value: production
        - name: TRAFFICPEAK_URL
          valueFrom:
            configMapKeyRef:
              name: trafficpeak-config
              key: url
        - name: TRAFFICPEAK_TOKEN
          valueFrom:
            secretKeyRef:
              name: trafficpeak-secrets
              key: api-token
        - name: TRAFFICPEAK_TABLE
          valueFrom:
            configMapKeyRef:
              name: trafficpeak-config
              key: table-name
        - name: TRAFFICPEAK_USERNAME
          valueFrom:
            secretKeyRef:
              name: trafficpeak-secrets
              key: username
        - name: TRAFFICPEAK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: trafficpeak-secrets
              key: password
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: event-processor
spec:
  selector:
    app: event-processor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
